# =============================================================================
# bird-1.6.8v6.conf — test BIRD 1.6.8 IPv6 daemon (started as `bird6`).
# =============================================================================

define RTR_IP  = 2001:db8:123::68;
define RTR_ASN = 65068;

router id 10.123.123.168;
log syslog all;
debug protocols all;

protocol device {}
protocol direct {}
protocol kernel { export all; learn; }
protocol static { import all; export all; }

filter reject_test_filtered {
    if net ~ [ 2001:db8:52::/48 ] then reject;
    accept;
}

protocol bgp rs1_ipv6 {
    source address RTR_IP;
    local as RTR_ASN;
    neighbor 2001:db8:123::10 as 65010;
    import filter reject_test_filtered;
    export all;
    import keep filtered;
}
protocol bgp rs2_ipv6 {
    source address RTR_IP;
    local as RTR_ASN;
    neighbor 2001:db8:123::20 as 65020;
    import all;
    export all;
}
